### ISSUE TITLE
定量目標を立てる

### ISSUE THREAD

**Issue by kiksan123** [shuyzn/AtCoder_Omeikan6F#4]
# 概要
- 自分の目標（色やパフォーマンス等）を決め、学習計画とToDoを立てる

# 設定項目
- 目標の色およびパフォーマンス
- その色になるためにどうするか
- 期限を切って計画をたてる

# ポンイチ例
## 目標
水色になる

## その色になるために
1. アルゴリズムを勉強する
- DFS
- BFS
- Union find
......comming soon

2.本で勉強する(3周する)
-  螺旋本
- チーター本
- 蟻本

3. 過去問を解く
- 1日最低2問

## 学習計画
comming soon

**Comment by shyz222** [comment]
iine:D
